### ISSUE TITLE
not working under DSM 6.1.1-15101 Update 1 anymore

### ISSUE THREAD

**Issue by atzetot** [aldostools/ps3netsvr#4]
Hey

compiled GIT sources with ipkg bootstrap under DSM 6.1.1-15101 Update 1.
Compilation works and psnetsrv starts.
Can log in via multiman and webman and browse net_host folders. (debugged via ssh)

When I select a JB folder (game) to be mounted in multiman I receive 
"The selected disc image is not a compliant PS3ISO, but may still be able to access it in other applications."
Pressing X results in XMB without any mounted image.

In webman I receive mounting error as well.

config:
rebug 4.78.2 REX, webman mod 1.47.05, mmCM 04.81.02, COBRA 7.30, rebug tools 02.02.12.
tried rebug rex 4.80.1 and 4.81.1 and 4.81.2 as well.

I am totally frustrated atm because I also tried docker with several images, entware compiled ps3netsrv and dirkvdb ps3netsrv via git, too. no success.

strangely when I use the windows version of ps3netsrv (https://github.com/aldostools/webMAN-MOD/releases) and point via windows to the net drive (\\something\GAMES) the JB mounting in webman und multiman works.

Please.... need some help. wasted my whole weekend compiling (entware, optware, virtualbox....)

Best regards
Atzetot

**Comment by bguerville** [comment]
Fyi, to use with multiman & sMan, deank always recommends using his former ps3netsrv, unmodded, available at http://deanbg.com/ps3netsrv.zip...

**Comment by atzetot** [comment]
Ultimately compiled it myself on DSM 6.1.2-15132 with bootstrap c++ environment.
runs flawless - https://goo.gl/ZwXfdi

**Comment by bguerville** [comment]
Good to hear.
What was the problem then? 
Any useful tip you might want to share?

**Comment by atzetot** [comment]
Could not compile aldos source code under dsm and used another source
template.

2017-06-19 13:29 GMT+02:00 bguerville <notifications@github.com>:

**Comment by bguerville** [comment]
Thanks for clarifying. 😉

**Comment by heilmoa** [comment]
How can i get the Binary to work on a Synology DS215J with the Armada375? Would be very nice if you could help me out. 
I already have a previous version installed, where i only had to change the package information in the SPK file, so the CPU and other information matched again. This package doesnt work anymore...
